#!/usr/bin/env bash
#commanline options
OPTIND=1
cp1=1
cp2=5
cp3=7
path=""
name="theme"
while getopts "b:s:t:i:f:" opt; do
	case "$opt" in
		b) cp1=$OPTARG
			;;
		s)  cp2=$OPTARG
			;;
		t)  cp3=$OPTARG
			;;
		i) name="$OPTARG"
			path="$HOME/Pictures/Bgs/$name" [ -f "$path" ] && wal -i $path || echo "file $path does not exist"
			;;
		f) name="$OPTARG"
			path="$HOME/dotfiles/schemes/$name"
			[ -f "$path" ] && wal -f $path || echo "file $path does not exist"
			;;
		:) echo "Option -$OPTARG requires am argument"
			exit 0;
			;;
    	esac
done

shift $((OPTIND-1))

[ "${1:-}" = "--" ] && shift
hc1="$(sed -n "$cp1 p" ~/.cache/wal/colors)"
hc2="$(sed -n "$cp2 p" ~/.cache/wal/colors | cut -c 2-)"
hc3="$(sed -n "$cp3 p" ~/.cache/wal/colors | cut -c 2-)"

dir=${name%.*}
mkdir $HOME/dotfiles/chrome/themes/$dir
cd $HOME/dotfiles/chrome/themes/$dir
echo "directory made"
mkdir images
cd images
convert xc:"$hc1"[20x1920!] theme_frame.png
convert xc:"$hc1"[20x120!] theme_tab_background.png
convert xc:"$hc1"[20x120!] theme_toolbar.png
echo "images generated"
hc1="$(sed '1q;d' ~/.cache/wal/colors | cut -c 2-)"
c1="$(bash hexrgb $hc1)"
c2="$(bash hexrgb $hc2)"
c3="$(bash hexrgb $hc3)"
cd ..
touch manifest.json
echo "{
	\"name\":\"$dir\",
	\"version\":\"1.0\",
	\"description\":\"Theme based off of Wal\",
	\"manifest_version\":2,
	\"theme\":{
		\"images\":{
			\"theme_frame\":\"images/theme_frame.png\",
			\"theme_toolbar\":\"images\/theme_toolbar.png\",
			\"theme_tab_background\":\"images\/theme_tab_background.png\"
		},
		\"colors\":{
			\"frame\":[$c1],
			\"toolbar\":[$c1],
			\"tab_text\":[$c2],
			\"tab_background_text\":[$c3],
			\"bookmark_text\":[$c3],
			\"ntp_background\":[$c1],
			\"ntp_text\":[$c3],
			\"control_background\":[$c3],
			\"button_background\":[$c3]
		},
		\"tints\":{
			\"buttons\":[1.0,0.84,0.0]
		},
		\"properties\":{
			\"ntp_background_alignment\":\"bottom\",
			\"ntp_background_repeat\":\"no-repeat\"
		}
	}
}" >> manifest.json
echo "manifest.json made"
cd ..
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --pack-extension="$HOME/dotfiles/chrome/themes/$dir"
echo ".crx made"
rm -rf $dir
rm *.pem
echo "excess deleted"
open "$dir.crx"
echo "opening $dir.crx..."
osascript $HOME/dotfiles/scripts/refresh.scpt
